config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    if params[:name]
      @flats = Flat.where('name LIKE ?', "%#{params[:name]}%")
    else
      @flats = Flat.all
    end
  end

  def show
    @flat = Flat.find(params[:id])
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else render :new
    end
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)
    if @flat.save
      redirect_to flats_path
    else render :new
    end
  end

  def destroy
    @flat = Flat.find(params[:id])
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night,
                                 :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<div class="container form">
  <h2>Edit a flat</h2>
    <br>
    <%= form_for @flat do |f| %>
      <p><%= f.label :name %></p>
      <p><%= f.text_field :name %></p>
      <p><%= f.label :address %></p>
      <p><%= f.text_field :address %></p>
      <p><%= f.label :description %></p>
      <p><%= f.text_area :description %></p>
      <p><%= f.label :price_per_night %></p>
      <p><%= f.text_field :price_per_night %></p>
      <p><%= f.label :number_of_guests %></p>
      <p><%= f.text_field :number_of_guests %></p>
      <br>
      <p><%= f.submit %>
    <% end %>
</div>

app/views/flats/index.html.erb
<div class="container">
  <h1>All our Flats (<%= @flats.count %>)</h1>

  <div class="card-list-container">
    <div class="card-list">
      <div class="row">
        <% @flats.each do |flat| %>
          <div class="col-xs-4">
            <div class="card">
              <div class="content" style="background-image:url('https://source.unsplash.com/random/?apartment'),linear-gradient(rgba(0, 0, 0, 0.3), rgba(0, 0, 0, 0.3));background-size:cover;background);">
                <h4><%= flat.name %></h4>
                <div class="flat-address"><%= flat.address %></div>
                <div class="icons">
                  <ul class='list-inline'>
                    <li><p><i class="fas fa-users"></i> <%= flat.number_of_guests %></p></li>
                    <li><p><i class="fas fa-euro-sign"></i> <%= flat.price_per_night %></p></li>
                  </ul>
                </div>
              </div>
              <div class="link">
                <%= link_to 'More Info', flat_path(flat), class: 'info-link' %>
                <%= link_to 'Edit', edit_flat_path(flat), class: 'edit-link' %>
                <%= link_to 'Delete', flat_path(flat), class: 'delete-link', method: :delete, data: { confirm: "Are you sure?" } %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/new.html.erb
<div class="container form">
  <h2>Add a new flat</h2>
    <br>
    <%= form_for @flat do |f| %>
      <p><%= f.label :name %></p>
      <p><%= f.text_field :name %></p>
      <p><%= f.label :address %></p>
      <p><%= f.text_field :address %></p>
      <p><%= f.label :description %></p>
      <p><%= f.text_area :description %></p>
      <p><%= f.label :price_per_night %></p>
      <p><%= f.text_field :price_per_night %></p>
      <p><%= f.label :number_of_guests %></p>
      <p><%= f.text_field :number_of_guests %></p>
      <br>
      <p><%= f.submit %>
    <% end %>
</div>

app/views/flats/show.html.erb
<div class="banner">
</div>
<div class="container-show">
  <div class="card-show">
    <div class="flat-info">
      <div class="flat-name">
        <h2><strong><%= @flat.name %></strong></h2>
        <h5><%= @flat.address %></h5>
      </div>
      <div class="flat-desc">
        <p><strong>A bit more about this flat...</strong></p>
        <p><%= @flat.description %></p>
      </div>
    </div>
    <div class="flat-info2">
      <div class="flat-details">
        <p><strong>Details</strong></p>
        <ul class='list-inline'>
          <li><p><i class="fas fa-users"></i> <%= @flat.number_of_guests %></p></li>
          <li><p><i class="fas fa-euro-sign"></i> <%= @flat.price_per_night %></p></li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-PmY9l28YgO4JwMKbTvgaS7XNZJ30MK9FAZjjzXtlqyZCqBY6X6bXIkM++IkyinN+" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">AirBnB</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Add Flat', new_flat_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
    <%= yield %>
  </body>
</html>